#!/bin/sh

id=$(xinput list --id-only "ELAN072B:00 04F3:30A0 Touchpad")

xinput set-prop $id "libinput Tapping Enabled" 1
xinput set-prop $id "libinput Tapping Drag Enabled" 0
# slower scroll (higher value - slower)
xinput set-prop $id "libinput Scrolling Pixel Distance" 40
